auth.js, ideareadme.md, package-lock.json, package.json, routes/users.js, views/layout.pug
Here's the newly finished and functioning sign-up route
=> sign-up done

app.js, auth.js, routes/index.js, routes/users.js, views/layout.pug, views/log-in.pug, views/sign-up.pug
=> logout complete

routes/users.js
=> fixed login bug

db/seeders/20220412162042-tagsData.js, db/seeders/20220412163400-usersData.js, db/seeders/20220412163653-questionsData.js, db/seeders/20220412164106-answersData.js, ideareadme.md
=> seeding complete

public/stylesheets/main.css, routes/questions.js, views/layout.pug, views/new-question.pug
added route for new question (post/get)
=> added router for new question page both post and get

routes/questions.js, views/question-detail.pug
We just started separate question page.
=> quesiton page route started

public/stylesheets/main.css, routes/questions.js, views/new-question.pug, views/update-question.pug
Updated some important things for editing our pages
=> Edit q done br

routes/users.js, views/layout.pug
=> Demo user Completed

public/javascripts/answers.js, routes/questions.js, views/new-answer.pug, views/question-detail.pug
=> create answers route function

public/javascripts/answers.js, routes/questions.js, views/question-detail.pug
Completed edit API for answer edit
=> Completed edit API for answer

app.js, routes/search.js, views/layout.pug
Currently in work with Searching Questions
=> Search result in progress

public/stylesheets/main.css, views/question-detail.pug
=> CSS for Answer page

public/stylesheets/main.css, views/new-answer.pug, views/new-question.pug, views/update-question.pug
=> Styling ans br

README.md, routes/questions.js
=> added README

public/stylesheets/main.css, views/index.pug, views/question-delete.pug
I fixed some margins so that all forms and displays are the same distance from the top of the screen. I also fixed the route from the cancel button on the delete question form, which was navigating to the home page. It now navigates back to the question detail page.
=> Minorspacestyles jh

public/stylesheets/main.css, routes/questions.js, views/question-detail.pug
added createdAt date for question-detail
=> Created date br2

public/stylesheets/main.css, views/tag.pug
=> styled multi tag select

public/stylesheets/main.css, views/index.pug, views/tag.pug
Added animation to main page tags, and edited styling for tag search page.
=> tag styling

public/stylesheets/main.css, views/index.pug
Some styling for view questions page
=> some styling on main page for questionDivMainPage

public/stylesheets/main.css
styling for view questions page
=> I don't know why it didn't push before

public/javascripts/search-results.js, public/stylesheets/main.css, views/search-results.pug
CSS to search results for better spread between tags and user. Changed up color for searched word
=> added some CSS in search-results

public/stylesheets/main.css, views/log-in.pug
=> work in progress for log in

public/javascripts/answers.js, public/stylesheets/main.css, views/layout.pug, views/new-answer.pug, views/new-question.pug, views/question-detail.pug, views/search-results.pug
fixed error where clicking to delete an answer, then cancelling that, would make the submit button for editing that answer also delete the answer
=> Formatting and errors jh

public/stylesheets/main.css
changed body back to flex and commented out absolute position for footer because footer was covering up the bottom of content on narrow pages
=> footer was covering content on narrow pages so made changes

public/stylesheets/main.css, views/new-answer.pug, views/update-question.pug
text area wasn't resizing on edit question page
=> textarea resize wasnt working on edit question page

README.md
formatted code snippets in README
=> formatted code snippets README

public/stylesheets/main.css, routes/search.js
Fixed error where searching for an empty string from a search results page returned a 404. also added blue glow to highlighted search terms on search results page
=> Search style jh
